function viewpick(box, rawfolder, nbrdatasets)

for datasetid = 1:nbrdatasets

    system( sprintf(['echo ''#!/bin/bash \n \n'...
                    'cd RawMicrographs/',rawfolder(datasetid).name,' && '...
                    'module purge && '...
                    'module load RELION/1.4-goolf-1.4.10 && '...
                    '`which relion_manualpick` '...
                    '--i "*.mrc" --o '...
                    '--pickname automatchAll --scale 0.2 '...
                    '--sigma_contrast 3 --black 0 --white 0 '...
                    '--lowpass 0 --angpix 1 --ctf_scale 1 '...
                    '--particle_diameter ',num2str(box),' && '...
                    ' cd ../.. '' > gautoviewpick.sh']) );
                

    system('source gautoviewpick.sh');

end